### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dav-is** [AmauryCarrade/flarum-ext-syndication#2]
You should switch to the MIT license or somehow make it so you don't need to put the whole license at the top of each file.

**Comment by AmauryCarrade** [comment]
It was only an habit, the CeCILL doesn't *requires* that but my IDE was configured like that. I can remove them if they annoy you, I don't really care. But I will keep the CeCILL-B (as it's a better license for me, in French law).

**Comment by dav-is** [comment]
It is a huge block of text that makes it a bit hard to quickly look through the code. Maybe just simply "See license file for more information" or whatever the typical convention is.
