### ISSUE TITLE
URLs readability

### ISSUE THREAD

**Issue by deseven** [AmauryCarrade/flarum-ext-syndication#3]
I have a small proposal to make urls more readable.
Right now you append /d to an url to output feed with discussions. It's not really obvious.

How about that:
`/atom/posts` - for feed with posts
`/atom/discussions` - for feed with discussions
`/atom` - defaults to `/posts`

Same thing for tags, users, etc.

**Comment by AmauryCarrade** [comment]
HI!

I agree with the `/discussions` instead of `/d` part. It would be clearer. For the others—the idea was to prepend `/rss/` or `/atom` to the URL to get the feed, that's why there is no `/posts` etc.

Feel free to repoen if you disagree :)
