### ISSUE TITLE
Generated feeds aren't valid

### ISSUE THREAD

**Issue by arthrfrts** [AmauryCarrade/flarum-ext-syndication#9]
Hi!

I'm using the Syndication extension to trigger an IFTTT applet. However, IFTTT requires the feed to be valid for it to work, and the extension isn't generating valid feeds (both RSS and Atom). Some data are returning just `1`, when it should be a post URL, for example.

[You can check the validator results for my feed here](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fforum.esporo.net%2Fatom). I'm using Beta 10.

**Comment by jee-r** [comment]
Hi,
I have a similar issue, my reader (tt-rss) detect only one entry and not even the last one.

**Comment by AmauryCarrade** [comment]
This is being fixed. I'm waiting on answer to my requests on the related PR #10 :)

**Comment by jee-r** [comment]
Ok :) sorry i didn't see the PR, thank you @AmauryCarrade

**Comment by AmauryCarrade** [comment]
No worries :)

12 octobre 2019 13:58 "Jee" <notifications@github.com (mailto:notifications@github.com?to=%22Jee%22%20<notifications@github.com>)> a écrit:
	Ok :) sorry i didn't see the PR, thank you @AmauryCarrade (https://github.com/AmauryCarrade)
